### ISSUE TITLE
Prevent bare toplevel commands from panicking

### ISSUE THREAD

**Issue by porglezomp** [porglezomp/canvas-cli#5]
Currently running something like `canvas file` will panic with:
```
thread 'main' panicked at 'internal error: entered unreachable code', src/main.rs:78:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
This shouldn't happen, instead we should run some default action like `canvas file help` or `canvas file ls` or something.

**Comment by kitlith** [comment]
Claiming this.

The issue is that `clap::AppSetting::ArgRequiredElseHelp` doesn't propegate down to subcommands, so you need to specify it on each subcommand.

also it doesn't build as-is.

**Comment by porglezomp** [comment]
It's been a while since I worked on this, feel free to upgrade the `clap` version while you're at it.
