### ISSUE TITLE
~/.config/canvas-cli should be automatically created if it doesn't exist, instead of just erroring out

### ISSUE THREAD

**Issue by kitlith** [porglezomp/canvas-cli#8]
See title. Something I ran into while investigating the other issue.

**Comment by porglezomp** [comment]
I think the ideal interface for this is bringing up a prompt asking for the needed values, along with the quick instructions for where to find them.

**Comment by kitlith** [comment]
Well, you already have this prompt (in the form of a separate command), the issue is even that command will fail if the folder doesn't exist.
